baseURL = 'https://cloudnative-pg.io'
languageCode = 'en-us'
title = 'CloudNativePG - PostgreSQL Operator for Kubernetes'
staticDir = ['assets']

[build]
  writeStats = true

[project]
  name = 'CloudNativePG'

[services]
  [services.googleAnalytics]
    id = 'G-SJWWHL48V3'

[params]
  description = 'CloudNativePG - PostgreSQL Operator for Kubernetes'
  images = ['images/hero_image.png']

[taxonomies]
  author = 'authors'
  tag = 'tags'
